#pragma once
#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <numeric>
#include <sstream>
#include <algorithm>
#include <fstream>
#include <chrono>
#include <deque>
#include <list>

using std::cout;
using std::cout;
using std::cin;
using std::setprecision;
using std::setw;
using std::left;
using std::right;
using std::string;
using std::vector;
using std::endl;
using std::istream;
using std::ostream;
